server {
    listen 80;
    listen [::]:80;
    server_name hoospreadsheet.net www.hoospreadsheet.net;
    include /www/server/panel/vhost/nginx/well-known/hoospreadsheet.net.conf;
    return 301 https://hoospreadsheet.net$request_uri;
}
server {
    listen 443 ssl;
    http2 on;
    server_name www.hoospreadsheet.net;
    ssl_certificate /www/server/panel/vhost/cert/hoospreadsheet.net/fullchain.pem;
    ssl_certificate_key /www/server/panel/vhost/cert/hoospreadsheet.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    return 301 https://hoospreadsheet.net$request_uri;
}
server {
    listen 443 ssl;
    http2 on;
    server_name hoospreadsheet.net;
    root /www/wwwroot/hoospreadsheet.net;
    index index.html index.htm;
    charset utf-8;
    ssl_certificate /www/server/panel/vhost/cert/hoospreadsheet.net/fullchain.pem;
    ssl_certificate_key /www/server/panel/vhost/cert/hoospreadsheet.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    include /www/server/panel/vhost/nginx/well-known/hoospreadsheet.net.conf;
    include /www/server/panel/vhost/nginx/extension/hoospreadsheet.net/*.conf;
    error_page 404 /404.html;
    location = /404.html { internal; }
    location /assets/ { expires 7d; }
    location / { try_files $uri $uri/ $uri/index.html =404; }
    access_log /www/wwwlogs/hoospreadsheet.net.log;
    error_log /www/wwwlogs/hoospreadsheet.net.error.log;
}
